on:
    push:
      branches: [ dev ]
        workflow_dispatch:
    # push:
    #   branches: [ "main" ]
    # pull_request:
    #   branches: [ "main" ]
  # on:
    # push:
    #   branches:
    #     - "latest"
    #   pull_request:
    #     - "main"
    
  jobs:
    build:
      runs-on: ubuntu-latest
      
      #  ci / cd automatic deploy to heroku
      #   deploy: ## <-- this is the new stuff
      # needs: build
      # runs-on: ubuntu-latest
      # steps:
      #   - uses: actions/checkout@v2
      #   - uses: akhileshns/heroku-deploy@v3.12.12
      #     with:
      #       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #       heroku_app_name: "micah-simple-node-api"
      #       heroku_email: "micah@afitnerd.com"
  
      strategy:
        matrix:
        node-version: [ 14.x, 15.x]
      
      steps:
          - uses: actions/checkout@v2
          - name: Use Node.js
            uses: actions/setup-node@v2
            with: 
              node-version: "14.x"
      
          - name: Install dependencies
            run: npm install
      
          - name: Run test
            run: npm test
  
  # HEROKU DEPLOYMENT
  #  build:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #       - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
  #         with:
  #           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #           heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
  #           heroku_email: "YOUR EMAIL"
  
      # steps:
      #   - uses: actions/checkout@v3
      #   - name: Use Node.js ${{ matrix.node-version }}
      #     uses: actions/setup-node@v3
      
      #   - name: Checkout
      #     uses: actions/checkout@v1
          
          
      #   # Runs a single command using the runners shell
      #   - name: Run a one-line script
      #     run: echo Hello, world!
          
      #   # Runs a set of commands using the runners shell
      #   - name: Run a multi-line script
      #     run: |
      #       echo Add other actions to build,
      #       echo test, and deploy your project.
  
      #   - name: Install and build
      #     run: npm install && npm run build
  
      #   - name: Deploy
      #     uses: JamesIves/github-pages-deploy-action@4.1.1
      #     with:
      #       branch: main
      #       folder: build
      #       node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
  w